"""new fields in user model

Revision ID: 445a27730cd1
Revises: 778aa78b69a9
Create Date: 2019-08-28 13:11:26.682263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445a27730cd1'
down_revision = '778aa78b69a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
